import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google"; // Replace Geist with supported Google fonts
import "./globals.css";

// Replace Geist with Inter (or any other Google Font)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Replace Geist_Mono with Roboto_Mono (or another Google Mono font)
const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
